sudo: false
language: go

go:
- 1.x
- master

before_script:
- cd v7
- go vet ./...

script:
- go test -json > report.json
- go test -coverprofile=coverage.txt -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)