sudo: false
language: go

go:
- 1.x
- master

before_script:
- cd v4
- go vet ./...

script:
- go test -v -coverprofile=coverage.txt -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)